### ISSUE TITLE
SDK Crashing when trying to play with tweak config

### ISSUE THREAD

**Issue by obaidjatoi** [bitmovin/bitmovin-api-sdk-examples#20]
when we are trying to implement below code, the app is crashing.

**Code :**
var tweak = OfflineTweaksConfig(false)
var offlineConfig = OfflineConfig(tweaksConfig = tweak)
OfflineContentManager.setOfflineConfig(contextAndroid , offlineConfig) 

**Crash** 
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{cdb450e u0 net.gadm.tv.beta/com.bitmovin.player.offline.service.BitmovinDownloadService}
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2191)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8125)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
        
**and all the download manager is in a Runnable**

**In our code, the context is fetched by this** 

private var contextWrapper: WeakReference<Context>? =  WeakReference(context.applicationContext)
contextWrapper?.get()

**Comment by luckygoyal-bitmovin** [comment]
@obaidjatoi , any specific reason to pass the context as weak reference? Can you please pass the Main Activity object or the Application's context as the context to` OfflineContentManager.setOfflineConfig`. Please note that you can do configuration only once as soon as you application's Main activity is created, you need not do it on every download workflow.

```
var tweak = OfflineTweaksConfig(false)
var offlineConfig = OfflineConfig(tweaksConfig = tweak)
OfflineContentManager.setOfflineConfig(contextAndroid , offlineConfig)
```

If you still face the issue, then please share a working sample app where the issue can be reproduced. I have checked in our sample application and the above configuration works fine without any crash.

**Comment by dreadjr** [comment]
@obaidjatoi What was the issue?
